name: safescan_flutter
description: "A Flutter application to scan QR codes and check link safety."
# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0' # Use the latest stable SDK range

dependencies:
  flutter:
    sdk: flutter

  # QR Code Scanning
  mobile_scanner: ^5.1.1 # Popular and well-maintained QR scanner

  # Networking
  http: ^1.2.1 # For making HTTP requests to the backend

  # State Management (Choose one or use simpler approaches for small apps)
  # provider: ^6.1.2 # A popular choice for state management
  # riverpod: ^2.5.1 # Another popular state management library

  # UI/UX Helpers
  # flutter_spinkit: ^5.2.1 # For loading indicators (optional)
  url_launcher: ^6.2.6 # To potentially open safe links (optional)
  permission_handler: ^11.3.1 # For handling camera permissions
  material_design_icons_flutter: ^7.0.7296 # For more icon options

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # For code analysis and linting

flutter:
  uses-material-design: true

  # Define assets (like images or fonts) if needed
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
